### ISSUE TITLE
FFmpeg Error of Some Sort

### ISSUE THREAD

**Issue by Jeydin21** [skick1234/DisTube-Example#2]
When I try to play a song using this template, I get an error that says
```js
An error encountered: Error: Cannot play `xpmQK_uPDpg:FFmpeg/aconv not found!`
```
What does this mean, and how can I fix it?

**Comment by skick1234** [comment]
Because you have not installed FFmpeg. It is required to use [DisTube](https://distube.js.org),
You can use this to install it automatically
```npm
npm install ffmpeg-static
```
Join [DisTube Support Server] to read the FAQ and get a faster response.

**Comment by Jeydin21** [comment]
Does it work on cloud hosters like Repl.it and Glitch and Heroku?

**Comment by skick1234** [comment]
Heroku will work, Glitch and repl.it doesn't support FFmpeg

-------
Join [DisTube Support Server](https://discord.gg/feaDd9h) to read the FAQ and get a faster response.

**Comment by Jeydin21** [comment]
Got it, thanks!
