### ISSUE TITLE
Unable to Retrieve Video Metadata error

### ISSUE THREAD

**Issue by Jeydin21** [skick1234/DisTube-Example#3]
When I try to play a song, it says "Unable to retrieve video metadata." How can I fix this? My bot is hosted on Heroku.
![Screen Shot 2020-11-14 at 1 30 49 PM](https://user-images.githubusercontent.com/62669147/99155472-c868a200-267d-11eb-9169-8a46e9238a4e.png)

**Comment by KeepSOBP** [comment]
fent/node-ytdl-core/issues/751

```bash
npm uninstall ytdl-core
npm install ytdl-core@4.0.3
```
To reduce metadata error
